
const ActionTypes = {
    hostdash: {
      FETCH_ROOMS_START: 'FETCH_ROOMS_START',
      FETCH_ROOMS_SUCCESS: 'FETCH_ROOMS_SUCCESS',
      FETCH_ROOMS_ERROR: 'FETCH_ROOMS_ERROR',
      DELETE_ROOM_START: 'DELETE_ROOM_START',
      DELETE_ROOM_SUCCESS: 'DELETE_ROOM_SUCCESS',
      DELETE_ROOM_ERROR: 'DELETE_ROOM_ERROR',
      ADD_ROOM_START: 'ADD_ROOM_START',
      ADD_ROOM_SUCCESS: 'ADD_ROOM_SUCCESS',
      ADD_ROOM_ERROR: 'ADD_ROOM_ERROR'
    },
    useragenda: {
      FETCH_AGENDA_START: 'FETCH_USER_AGENDA_START',
      FETCH_AGENDA_SUCCESS: 'FETCH_USER_AGENDA_SUCCESS',
      FETCH_AGENDA_ERROR: 'FETCH_USER_AGENDA_ERROR',
    },
    hostagenda: {
      FETCH_AGENDA_START: 'FETCH_HOST_AGENDA_START',
      FETCH_AGENDA_SUCCESS: 'FETCH_HOST_AGENDA_SUCCESS',
      FETCH_AGENDA_ERROR: 'FETCH_HOST_AGENDA_ERROR',
      UPDATE_AGENDA_START: 'UPDATE_AGENDA_START',
      UPDATE_AGENDA_SUCCESS: 'UPDATE_AGENDA_SUCCESS',
      UPDATE_AGENDA_ERROR: 'UPDATE_AGENDA_ERROR',
      TOGGLE_EDIT: 'TOGGLE_EDIT',
      ADD_POLL: 'ADD_POLL',
      DELETE_POLL: 'DELETE_POLL',
      UPDATE_ORDER: 'UPDATE_ORDER'
    },
};

export default ActionTypes;
